a = (input('Digite Algo: '))
print('o tipo primitivo desse valor é:', type(a))
print('So tem espacos? ', a.isspace())
print('So tem numeros? ', a.isnumeric())
print('é alfabetico? ', a.isalpha())
print('é alfanumerico? ', a.isalnum())
print('Esta em maiusculo? ', a.isupper())
print('Esta em minusculo? ', a.islower())
print('Esta capitalizado? ', a.istitle())